### ISSUE TITLE
Present modal before view appearing

### ISSUE THREAD

**Issue by Xpressive** [avito-tech/Marshroute#12]
Is there any way to present modal controller before the user will see parent view? I'm using presentModalNavigationControllerWithRootViewControllerDerivedFrom, but it doesn't work in viewWillAppear or viewDidLoad(just nothing happens)

**Comment by Usipov** [comment]
@Xpressive, Hi.

`Marshroute` simply uses `UIKit` methods to implement navigation transitions.
So `presentModalNavigationControllerWithRootViewControllerDerivedFrom` ends up with

```
context.sourceViewController.present(
    context.targetNavigationController,
    animated: shouldAnimate,
    completion: nil
)
```

Can you reproduce the issue in a [demo](https://github.com/avito-tech/Marshroute/tree/master/Example) project? 
I failed to do so. I will push my branch a bit later to demostrate it.

Questions for further investigation:
1. How do you set up `Marshroute`? 
2. How do you present your parent view?
You probably push a view controller (A), and in its `viewWillAppear` you present another view controller (B)? In this the case? For me it works fine. 
It can break only along with `UIKit`'s restrictions, for example:
- pushing several view controllers during app's start may break the `UINavigationController`'s stack.
- presenting several controllers one by one may fail with something like `unbalances calls to begin/end appearance transitions`.

**Comment by Xpressive** [comment]
@Usipov Thank you for quick reply!

I think that it really depends on app start, because i'm trying to do this in application presenter(tab bar like in you demo app). You can replicate that in demo project adding this line to `ApplicationPresenter`:
```
view?.onViewWillAppear = { [weak self] in
            self?.showAuthorizationModule(nil)
        }
```
and changing behaviour of `showAuthorization` in `ApplicationRouter` to `presentModalNavigationControllerWithRootViewControllerDerivedFrom`. 

But maybe it is just bad practice. In my case, i just wanna prevent using app before authorization, so if there is no user credentials, i need to `showAuthorizationModule`.  Is there any cute ways to do this using `Marshroute`, or i need smth like coordinator?

**Comment by Usipov** [comment]
@Xpressive, Thanks for the detailed steps.
I reproduced the case and found the following logs in the debugger console:
```
Warning: Attempt to present <UINavigationController: 0x7fb58882f400> on <NavigationDemo.CategoriesViewController: 0x7fb586033800> whose view is not in the window hierarchy!
```

This simply means `UIKit` is not ready for performing transitions.

You can add a kludge like this
```
view?.onViewWillAppear = { [weak self] in
    DispatchQueue.main.async {
        self?.showAuthorizationModule(nil)
    }
}
```

Or a less kludge like this:
```
view?.onViewDidAppear = { [weak self] in
    self?.showAuthorizationModule(nil)
}
```

`UIKit` is lots of fun =)

**Comment by Xpressive** [comment]
@Usipov Thank you for detailed answer 👍  

I've tried to do this in `viewDidAppear`, but delay was too long. Your first solution works awesome, thanks! 

I wish the best for your project, and waiting for new updates :)
