### ISSUE TITLE
Migrate to swift 4.2

### ISSUE THREAD

**Issue by bengus** [avito-tech/Marshroute#14]
Now there are a lot of warnings when you try to build it in swift 4.2 project with Xcode 10.1. I will try to provide a pull request with fix.
![2019-01-19 15 40 41](https://user-images.githubusercontent.com/6199081/51426788-9fe9fb00-1c00-11e9-9d97-591e3309e5b0.jpg)

**Comment by Usipov** [comment]
@bengus, thanks for the report
I'll take a look at it later in January

**Comment by vladimir-kaltyrin** [comment]
@Usipov Awesome, thanks for the fix 🎉

**Comment by Usipov** [comment]
@vladimir-kaltyrin, lol, how are you =)
Marshroute supports swift 5 (since 2021 or 2022 i guess). Just forgot to close the issue
Today I pushed some breaking changes and bumped version to 1.0.0

**Comment by khomTima** [comment]
hi there, great library btw!
