### ISSUE TITLE
The pod has a folder that doesn't compile on a non-UNIX system

### ISSUE THREAD

**Issue by JasperAppec** [avito-tech/Marshroute#6]
In this directory: `Marshroute/Marshroute/Sources/Transitions/TransitionAnimations/Navigation/`, there's a folder called `Push/Pop`. Cloning a repository on a Windows system (for example) that has this cocoapod, makes the git checkout not work. It complains that the folder `Push:Pop` is an invalid argument.

**Comment by Usipov** [comment]
@jasperrietrae, the fix complete. pushed new `0.3.6` version

Can you satisfy my interest by explaining your situation? `Marshroute` on `Windows` in `Netherlands` seem like a crazy mix

**Comment by JasperAppec** [comment]
@Usipov thanks.
Not sure what's weird about me living in The Netherlands? 😉  As for running an iOS library on a Windows system: I prefer a GUI for some specific Git tasks on a tool that is only available for Windows, but discovered that I was unable to clone or fetch a project of mine which uses Marshroute. That's all.

**Comment by Usipov** [comment]
@jasperrietrae, read `Netherlands` in your profile.
Happy using!
